controller_list:
  - name: fake_manipulator_controller
    type: $(arg execution_type)
    joints:
      - shoulder_1_joint
      - shoulder_2_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      - _ezgripper_knuckle_palm_L1_1
      - _ezgripper_knuckle_L1_L2_1
initial:  # Define initial robot poses.
  - group: manipulator
    pose: test_pose